# nixpacks.toml
[phases.setup]
nixPkgs = ["python310", "gcc", "libGL", "libGLU", "glib", "libSM", "libXext", "libXrender", "libgomp"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "python main.py"